### PR TITLE
Support https

### PR DESCRIPTION
**Pull request by davars**

### CODE REVIEW

**Comment by dnaeon** [comment]
Merged, thanks a lot!

**Comment by dnaeon** [comment]
Please add your name to the authors file as well :)

**Comment by dnaeon** [comment]
@davars, seems like there has been an issue after merging this PR.

The issue is that new recordings are not possible and result in panics if you try to do new recordings.

This does not affect replaying of cassette data, but only when the recorder is running in recording mode.

Could you please have a look at this one? Easiest way to re-produce this is to simply  remove the existing cassette files and re-run the tests.

Meanwhile I will revert the commits from master, so that it doesn't affect other people. I will also have to add a test for recording from empty cassettes as well, so that we can catch such issues in the future.

Thanks for your work on this one!

**Comment by davars** [comment]
Hmm, I'm investigating.

**Comment by dnaeon** [comment]
Thanks, @davars!

**Pull request merged**
