### PR TITLE
Add DiscardOnSave field to Interaction type

### PR DESCRIPTION
**Pull request by dnaeon**
The DiscardOnSave field may be set to true by hooks, in order to discard an interaction before saving it on disk.

See issue #80 for some background info.

### CODE REVIEW

**Comment by dnaeon** [comment]
@sergiught , please check this one out and let me know how it looks. Thanks!

**Comment by sergiught** [comment]
Hey @dnaeon 👋🏻 ,

Thanks a lot for the quick turnaround! I was able to open a draft PR with the changes brought here within -> https://github.com/auth0/terraform-provider-auth0/pull/382/files#diff-54a6153bd2ec74433ca48fda4f010eadce4412bd67975099b4d2095f3396ebcfL825 and I can confirm this works like a charm.

**Review by sergiught — APPROVED** [review]

**Comment by dnaeon** [comment]
Hey @sergiught , thanks! Merged and tagged!

**Comment by jsoriano** [comment]
@dnaeon @sergiught is it possible that after this change it is needed to re-generate the recorded interactions?

We have found that when updating from 3.2.0 to 3.2.1 interactions cannot be found: https://github.com/elastic/elastic-package/pull/2001

In our case it would be quite burdensome to regenerate all interactions.

**Comment by jsoriano** [comment]
Ah sorry, ignore my comment, I checked the incorrect release :facepalm:

**Pull request merged**
