### PR TITLE
Record and respect request duration

### PR DESCRIPTION
**Pull request by dnaeon**
Probably a better way would be to use here `net/http/httptrace` instead. I'm opening this up here for discussion.

Related to #62

### CODE REVIEW

**Review by JVecsei — COMMENTED** [review]
Hey @dnaeon, 

first of all, thanks for the quick reaction! 
Works like a charm 👍 . I agree, you might get more accurate numbers with `httptrace`, on the other hand I'm not sure if there are many use cases where this is required, especially cause _real_ request times also generally vary. 

Does it make sense to have the duration feature configurable? I'm sure there are people who use this library for different reasons and might want to keep the "fast" tests without latency.

Also, I assume this will have to go to a new major version as this is a breaking change (the parsing of existing recordings doesn't work anymore because of the empty duration strings).

**Comment by dnaeon** [comment]
Hey @JVecsei ,

I've just added another commit which allows skipping the recorded request latency during replay. In order to do that simply set `SkipRequestLatency` to `true` after creating a new recorder.

The code as it is now should be compatible with older clients as well, since the recorded duration was never set before.

Can you please also test the new commit and let me know if it looks good?

Thanks!

**Comment by JVecsei** [comment]
Hi @dnaeon,

the flag works great. Thank you!
Regarding the older clients: Since the duration didn't have an `omitempty` in its struct tag, the existing recordings all have an empty duration string:

```yaml
duration: ""
```

So this would fail now with this error:

```
simple_test.go:40: yaml: unmarshal errors:
          line 27: cannot unmarshal !!str `` into time.Duration
          line 178: cannot unmarshal !!str `` into time.Duration
```

**Comment by dnaeon** [comment]
> So I think either it has to be changed back to manually parsing it after reading the file or having this as a feature in the next major release. What do you think?

You are totally correct. I'll have to finish my cup of coffee next time I reply :)

I think having this as a new major version makes sense, even if it is for this little feature. I'll make sure to tag this one as `v2.0.0` before releasing.

**Comment by JVecsei** [comment]
Perfect - I think this is a great addition to the library.
Thanks again for the quick realization! 👍

**Comment by dnaeon** [comment]
Just tagged `v2.0.0`.

https://github.com/dnaeon/go-vcr/releases/tag/v2.0.0

Thanks!

**Comment by JVecsei** [comment]
In case of a new major release there are a few more things to change to make it usable: [major version suffix](https://golang.org/ref/mod#major-version-suffixes), see also here: [Releasing Modules (v2 or Higher)](https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher)

**Pull request merged**
